import { createReducer } from "@reduxjs/toolkit";

const initialState = {
    col1: [
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: false, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: false, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: false, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: false, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: false, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: false, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: false, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: false, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: false, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
    ],
    col2: [
        { empty: true, selected: false },
        { empty: false, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: false, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: false, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: false, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: false, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: false, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: false, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: false, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
        { empty: false, selected: false },
        { empty: true, selected: false },
        { empty: true, selected: false },
    ]
}

const customeReducer2 = createReducer(initialState, {
    selectSeatCol1: (state, action) => { state.col1 = action.payload; },
    selectSeatCol2: (state, action) => { state.col2 = action.payload; },
    reset: (state, action) => {
        state.col1 = initialState.col1;
        state.col2 = initialState.col2;
    },
})

export default customeReducer2;